config/routes.rb
Rails.application.routes.draw do
  root to: "blogs#index"
<<<<<<< HEAD
  resources :blogs do
    get 'search', to: 'blogs#search', as: 'search'
  end
  resources :categories, except: [:new, :show]
  
=======
  resources :blogs
>>>>>>> parent of ed72fc0 (カテゴリ機能追加)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
<<<<<<< HEAD
  belongs_to :category
  
  validates :title,       presence: true
  validates :content,     presence: true
  validates :start_time,  presence: true
  validates :category_id, presence: true
=======
>>>>>>> parent of ed72fc0 (カテゴリ機能追加)
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blogs, class_name: 'Blog', foreign_key: 'category_id'
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
    @blog = Blog.new
  end
  
  def new
    @blog = Blog.new
  end
  
  def show
    @blog = Blog.find(params[:id])
  end
  
  def create
    Blog.create(blog_parameter)
    redirect_to blogs_path
  end
  
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blog_path
    else
      render edit
    end
  end
  
  private
  
  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>
  
  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>
  
  <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>
  
  <div class="submit">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/blogs/index.html.erb
<div class="container pt-5">
  <div class="row mt-5">
    <div class="col-md-4 mt-5">
      <h3>予定作成</h3>
      <%= form_with(model: @blog, local: true) do |form| %>
        <div class="title">
          <div class="form-tag">タイトル</div>
          <%= form.text_field :title %>
        </div>
        
        <div class="content">
          <div class="form-tag">内容</div>
          <%= form.text_field :content %>
        </div>
        
        <div class="time">
          <div class="form-tag">時間</div>
          <%= form.datetime_select :start_time %>
        </div>
        
        <div class="submit">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
    
    <div class="col-md-8 mt-5">
      <%= month_calendar events: @blogs do |date, blogs| %>
        <%= date.day %>
        
        <% blogs.each do |blog| %>
          <div style="font-size:13px;">
            <%= link_to blog.title, blog, class: "text-decoration-none", style: "color:black" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="show">
  <h1>
    <%= @blog.start_time.strftime("%m月%d日") %>
  </h1>
  
  <p>
    <strong>時間</strong>
    <%= @blog.start_time.strftime("%H:%M") %>
  </p>
  
  <p>
    <strong>タイトル</strong>
    <%= @blog.title %>
  </p>
  
  <p>
    <strong>内容</strong>
    <%= @blog.content %>
  </p>
  
  <%= link_to "編集", edit_blog_path(@blog) %>
  <%= link_to "消去", blog_path(@blog.id), data: { turbo_method: :delete } %>
  <%= link_to "戻る", blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '◁'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '▷'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading text-center" style="font-size:30px;">
    <%= link_to t('simple_calendar.previous', default: '◁'), calendar.url_for_previous_view, class: "text-decoration-none", style: "color:black" %>
    <span class="calendar-title"><%= start_date.year %> / <%= t('date.month_names')[start_date.month] %> </span>
    <%= link_to t('simple_calendar.next', default: '▷'), calendar.url_for_next_view, class: "text-decoration-none", style: "color:black" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '◁'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: '▷'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>